### ISSUE TITLE
raw dump of etymology dictionary

### ISSUE THREAD

**Issue by damooo** [vanangamudi/tharavukkanam#1]
@vanangamudi anna,
can you also make raw dump of etymdict available?, so that it can be used to create human readable offline dictionaries, like for golden dict etc. like at https://github.com/indic-dict/stardict-tamil

**Comment by damooo** [comment]
Anna,
It will be great, if you can provide raw dump, so that it can be used as normal dictionary too. i tried scraping with script, but as it is through selenium, it seems will take many days, and persistent internet connection, even if did in batches. as you may already have raw dump, it will be helpful if you push that one too.

**Comment by vanangamudi** [comment]
Sorry for the delayed response. You can download the raw dump of the dictionary [here](https://drive.google.com/open?id=114M2s_z_BfSorws_8AytuSnCt3Er4Rzb)

**Comment by damooo** [comment]
Thanks alot anna. i will create a stardict package, and return back.
