### ISSUE TITLE
wiki dump for tamil

### ISSUE THREAD

**Issue by RathaRR** [vanangamudi/tharavukkanam#2]
Could you please send me the direct link to download wiki tamil and tamil corpora?

**Comment by vanangamudi** [comment]
You can download the wikipedia dump from [here](https://dumps.wikimedia.org/tawiki/20200720/) 
What do you mean by tamil corpora? There is no canonical corpus for Tamil like BNC for english

Here I gather and try to integrate the corpora that I can find online and ones that I build.
